/**
 * AIReport
 * Props:
 *   report {
 *     executiveSummary  string
 *     insights          string[]
 *     recommendations   string[]
 *   }
 */
export default function AIReport({ report }) {
  if (!report) return null

  const { executiveSummary, insights = [], recommendations = [] } = report

  return (
    <div className="card overflow-hidden">
      {/* Header */}
      <div
        className="px-6 py-4 flex items-center gap-3"
        style={{ borderBottom: '1px solid var(--border)', background: 'rgba(0,212,170,0.03)' }}
      >
        <span className="text-xl">🧾</span>
        <div>
          <p
            className="font-bold"
            style={{ fontFamily: 'Syne, sans-serif', fontSize: '1rem' }}
          >
            AI Forensic Report
          </p>
          <p style={{ fontFamily: 'JetBrains Mono, monospace', fontSize: '0.66rem', color: 'var(--muted)' }}>
            Generated by LLM · Court-ready summary
          </p>
        </div>
        <button
          className="ml-auto btn-primary !py-2 !px-4 !text-xs"
          onClick={() => alert('PDF export — wire to /api/export-pdf')}
        >
          📄 Export PDF
        </button>
      </div>

      <div className="p-6 flex flex-col gap-6">
        {/* Executive Summary */}
        {executiveSummary && (
          <div>
            <p className="section-label" style={{ marginBottom: 10 }}>Executive Summary</p>
            <p className="leading-relaxed text-sm" style={{ color: 'var(--muted)', fontWeight: 300 }}>
              {executiveSummary}
            </p>
          </div>
        )}

        <div className="grid grid-cols-2 gap-6">
          {/* Insights */}
          {insights.length > 0 && (
            <div>
              <p className="section-label" style={{ marginBottom: 12 }}>Key Insights</p>
              <ul className="flex flex-col gap-3">
                {insights.map((insight, i) => (
                  <li key={i} className="flex items-start gap-3 text-sm leading-relaxed" style={{ color: 'var(--muted)' }}>
                    <span className="dot-amber" style={{ marginTop: 6 }} />
                    {insight}
                  </li>
                ))}
              </ul>
            </div>
          )}

          {/* Recommendations */}
          {recommendations.length > 0 && (
            <div>
              <p className="section-label" style={{ marginBottom: 12 }}>Recommendations</p>
              <ul className="flex flex-col gap-3">
                {recommendations.map((rec, i) => (
                  <li key={i} className="flex items-start gap-3 text-sm leading-relaxed" style={{ color: 'var(--muted)' }}>
                    <span className="dot-teal" style={{ marginTop: 6 }} />
                    {rec}
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
